# Generated by Django 5.0.4 on 2024-05-18 07:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(verbose_name='حداقل سن')),
                ('max_age', models.IntegerField(verbose_name='حداکثر سن')),
                ('name', models.CharField(choices=[('BABY', 'خردسال'), ('CHILD', 'کودک'), ('TEEN', 'نوجوان'), ('ADULT', 'جوان'), ('MIDDLE_AGED', 'میانسال'), ('ELDER', 'سالمند')], max_length=20, verbose_name='نام رده سنی')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام بیماری')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='cms_disease_name_b86e80_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdditionalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام اضافی')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_name', to='cms.disease')),
            ],
            options={
                'verbose_name': 'Add Names Disease',
            },
        ),
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گیاه')),
                ('herb_flavor', models.CharField(blank=True, choices=[('SWEET', 'شیرین'), ('SOUR', 'ترش'), ('BITTER', 'تلخ'), ('FAST', 'تند')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه')),
                ('temperament', models.CharField(choices=[('COLD', 'سرد'), ('HOT', 'گرم'), ('BOTH', 'هردو')], default='COLD', help_text='Select the temperament category of the herb.', max_length=10, verbose_name='طبع گیاه')),
                ('inappropriate_age_ranges', models.ManyToManyField(blank=True, to='cms.agerange', verbose_name='بازه\u200cهای سنی نامناسب')),
                ('interaction_herb', models.ManyToManyField(blank=True, to='cms.herb', verbose_name='تداخل گیاهان')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uposts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reply', models.BooleanField(default=False)),
                ('body', models.TextField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcomments', to='cms.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucomments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcomments', to='cms.post')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvote', to='cms.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uvote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('SPRING', 'بهار'), ('SUMMER', 'تابستان'), ('AUTUMN', 'پاییز'), ('WINTER', 'زمستان')], max_length=10)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(3)])),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_scores', to='cms.herb')),
            ],
            options={
                'unique_together': {('herb', 'season')},
            },
        ),
        migrations.CreateModel(
            name='Suitability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_states', models.CharField(blank=True, choices=[('consultation_needed', 'نیاز به مشورت به پزشک دارد'), ('contradiction', 'تعارض دارد')], max_length=100, null=True, verbose_name='حالات هشدار')),
                ('score', models.IntegerField(choices=[(3, 'درمان اول'), (2, 'درمان دوم'), (1, 'درمان سوم'), (-1, 'توصیه نمیشود'), (-100, 'قدغن است')], verbose_name='اولویت درمان')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suitability_disease', to='cms.disease', verbose_name='بیماری')),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suitability_herb', to='cms.herb', verbose_name='گیاه')),
            ],
            options={
                'unique_together': {('herb', 'disease')},
            },
        ),
    ]
