# Generated by Django 5.0.4 on 2024-05-04 19:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Description', verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('temperament', models.CharField(choices=[('COLD', 'سرد'), ('HOT', 'گرم'), ('BOTH', 'هردو')], default='COLD', help_text='Select the temperament category of the herb.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NeutralPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('SPRING', 'بهار'), ('SUMMER', 'تابستان'), ('AUTUMN', 'پاییز'), ('WINTER', 'زمستان')], max_length=10)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(3)])),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_scores', to='cms.herb')),
            ],
            options={
                'unique_together': {('herb', 'season')},
            },
        ),
        migrations.CreateModel(
            name='Suitability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negative_effects', models.CharField(blank=True, choices=[('consultation_needed', 'نیاز به مشورت به پزشک دارد'), ('contradiction', 'تعارض دارد'), ('prohibited', 'قدغن است')], max_length=100, null=True, verbose_name='حالت منفی')),
                ('score', models.IntegerField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suitability_disease', to='cms.disease')),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suitability_herb', to='cms.herb')),
            ],
            options={
                'unique_together': {('herb', 'disease')},
            },
        ),
        migrations.CreateModel(
            name='UserDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.disease', verbose_name='بیماری')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'unique_together': {('user', 'disease')},
            },
        ),
    ]
