# Generated by Django 5.0.4 on 2024-05-04 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerbInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیح تداخل')),
                ('herb1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_herb1', to='cms.herb')),
                ('herb2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_herb2', to='cms.herb')),
            ],
            options={
                'unique_together': {('herb1', 'herb2')},
            },
        ),
    ]
