# Generated by Django 5.0.4 on 2024-05-23 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('SWEET', 'شیرین'), ('FAST', 'تند'), ('BITTER', 'تلخ'), ('SOUR', 'ترش')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
        migrations.AlterField(
            model_name='seasonalscore',
            name='score',
            field=models.IntegerField(choices=[(2, 'اولویت اول'), (1, 'اولویت دوم'), (-1, 'توصیه نمیشود'), (-2, 'تشدیدکننده ی آلرژی')]),
        ),
        migrations.CreateModel(
            name='JobPollutionLevelScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_pollution_level', models.CharField(blank=True, choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('MUCH', 'زیاد'), ('POLLUTED_JOBS', 'مشاغل آلوده')], max_length=14)),
                ('score', models.IntegerField(choices=[(2, 'اولویت اول'), (1, 'اولویت دوم'), (-1, 'با احتیاط مصرف شود'), (-2, 'توصیه نمیشود')], default='2')),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollution_scores', to='cms.herb')),
            ],
            options={
                'unique_together': {('herb', 'job_pollution_level')},
            },
        ),
        migrations.CreateModel(
            name='JobScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('STUDENT', 'دانشجو'), ('EMPLOYEE', 'کارمند'), ('WORKER', 'کارگر'), ('SALESPERSON', 'فروشنده'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('HARD_JOBS', 'مشاغل سخت'), ('ATHLETE', 'ورزشکار'), ('HOUSEKEEPER', 'خانه دار'), ('MANAGEMENT', 'مدیریت')], max_length=14)),
                ('score', models.IntegerField(choices=[(2, 'عالی'), (1, 'خوب'), (0, 'خنثی'), (-1, 'با احتیاط مصرف کنند'), (-2, 'توصیه نمیشود')], default='0')),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_scores', to='cms.herb')),
            ],
            options={
                'unique_together': {('herb', 'job_type')},
            },
        ),
    ]
