# Generated by Django 5.0.4 on 2024-06-05 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPollutionLevelScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_pollution', models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('MUCH', 'زیاد'), ('POLLUTED_JOBS', 'مشاغل آلوده')], max_length=14)),
                ('score', models.IntegerField(choices=[(1, 'خوب'), (0, 'خنثی'), (-1, 'توصیه نمیشود'), (-100, 'قدغن است')])),
            ],
        ),
        migrations.CreateModel(
            name='JobScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('STUDENT', 'دانشجو'), ('EMPLOYEE', 'کارمند'), ('WORKER', 'کارگر'), ('SALESPERSON', 'فروشنده'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('HARD_JOBS', 'مشاغل سخت'), ('ATHLETE', 'ورزشکار'), ('HOUSEKEEPER', 'خانه دار'), ('MANAGEMENT', 'مدیریت')], max_length=14)),
                ('score', models.IntegerField(choices=[(1, 'خوب'), (0, 'خنثی'), (-1, 'توصیه نمیشود'), (-100, 'قدغن است')])),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AddField(
            model_name='seasonalscore',
            name='allergy_aggravator',
            field=models.CharField(choices=[('YES', 'بله'), ('NO', 'خیر')], default='NO', max_length=3, verbose_name='تشدیدکننده ی  آلرژی فصلی'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('BITTER', 'تلخ'), ('SOUR', 'ترش'), ('FAST', 'تند'), ('SWEET', 'شیرین')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_uposts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seasonalscore',
            name='score',
            field=models.IntegerField(choices=[(3, 'اولویت اول'), (2, 'اولویت دوم'), (1, 'اولویت سوم'), (-1, 'توصیه نمیشود'), (-100, 'قدغن است')], verbose_name='اولویت درمان'),
        ),
        migrations.AlterField(
            model_name='seasonalscore',
            name='season',
            field=models.CharField(choices=[('SPRING', 'بهار'), ('SUMMER', 'تابستان'), ('AUTUMN', 'پاییز'), ('WINTER', 'زمستان')], max_length=10, verbose_name='فصل'),
        ),
        migrations.AlterField(
            model_name='suitability',
            name='alert_states',
            field=models.CharField(blank=True, choices=[('consultation_needed', 'نیاز به مشورت به پزشک دارد')], max_length=100, null=True, verbose_name='حالات هشدار'),
        ),
        migrations.AddField(
            model_name='jobpollutionlevelscore',
            name='herb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollution_scores', to='cms.herb'),
        ),
        migrations.AddField(
            model_name='jobscore',
            name='herb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_scores', to='cms.herb'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AlterUniqueTogether(
            name='jobpollutionlevelscore',
            unique_together={('herb', 'job_pollution')},
        ),
        migrations.AlterUniqueTogether(
            name='jobscore',
            unique_together={('herb', 'job_type')},
        ),
    ]
