# Generated by Django 5.0.4 on 2024-05-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_herb_herb_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('FAST', 'تند'), ('BITTER', 'تلخ'), ('SOUR', 'ترش'), ('SWEET', 'شیرین')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
    ]
