# Generated by Django 5.0.4 on 2024-06-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_herb_herb_flavor_alter_seasonalscore_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalscore',
            name='allergy_aggravator',
            field=models.CharField(choices=[('YES', 'بله'), ('NO', 'خیر')], default='NO', max_length=3, verbose_name='تشدیدکننده ی  آلرژی فصلی'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('BITTER', 'تلخ'), ('FAST', 'تند'), ('SWEET', 'شیرین'), ('SOUR', 'ترش')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
        migrations.AlterField(
            model_name='seasonalscore',
            name='score',
            field=models.IntegerField(choices=[(3, 'اولویت اول'), (2, 'اولویت دوم'), (1, 'اولویت سوم'), (-1, 'توصیه نمیشود'), (-100, 'قدغن است')], verbose_name='اولویت درمان'),
        ),
        migrations.AlterField(
            model_name='seasonalscore',
            name='season',
            field=models.CharField(choices=[('SPRING', 'بهار'), ('SUMMER', 'تابستان'), ('AUTUMN', 'پاییز'), ('WINTER', 'زمستان')], max_length=10, verbose_name='فصل'),
        ),
        migrations.AlterField(
            model_name='suitability',
            name='alert_states',
            field=models.CharField(blank=True, choices=[('consultation_needed', 'نیاز به مشورت به پزشک دارد')], max_length=100, null=True, verbose_name='حالات هشدار'),
        ),
    ]
