# Generated by Django 5.0.4 on 2024-06-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_jobpollutionlevelscore_jobscore_remove_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('FAST', 'تند'), ('SWEET', 'شیرین'), ('SOUR', 'ترش'), ('BITTER', 'تلخ')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
