# Generated by Django 5.0.4 on 2024-05-04 21:29

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_herbinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitability',
            name='score',
            field=models.IntegerField(validators=[cms.models.validate_score]),
        ),
    ]
