# Generated by Django 5.0.4 on 2024-06-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_seasonalscore_allergy_aggravator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('FAST', 'تند'), ('SWEET', 'شیرین'), ('SOUR', 'ترش'), ('BITTER', 'تلخ')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
        migrations.AlterField(
            model_name='jobpollutionlevelscore',
            name='score',
            field=models.IntegerField(choices=[(1, 'خوب'), (0, 'خنثی'), (-1, 'توصیه نمیشود'), (-100, 'قدغن است')], default='0'),
        ),
        migrations.AlterField(
            model_name='jobscore',
            name='score',
            field=models.IntegerField(choices=[(1, 'خوب'), (0, 'خنثی'), (-1, 'توصیه نمیشود'), (-100, 'قدغن است')], default='0'),
        ),
    ]
