# Generated by Django 5.0.4 on 2024-06-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_herb_herb_flavor_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('FAST', 'تند'), ('SOUR', 'ترش'), ('SWEET', 'شیرین'), ('BITTER', 'تلخ')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
    ]
