# Generated by Django 5.0.4 on 2024-05-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_suitability_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(verbose_name='حداقل سن')),
                ('max_age', models.IntegerField(verbose_name='حداکثر سن')),
            ],
        ),
        migrations.AddField(
            model_name='herb',
            name='inappropriate_age_ranges',
            field=models.ManyToManyField(blank=True, to='cms.agerange', verbose_name='بازه\u200cهای سنی نامناسب'),
        ),
    ]
