# Generated by Django 5.0.4 on 2024-06-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_herb_herb_flavor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('BITTER', 'تلخ'), ('FAST', 'تند'), ('SOUR', 'ترش'), ('SWEET', 'شیرین')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
        migrations.AlterField(
            model_name='jobpollutionlevelscore',
            name='job_pollution',
            field=models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('MUCH', 'زیاد'), ('POLLUTED_JOBS', 'مشاغل آلوده')], default='MEDIUM', max_length=14),
        ),
        migrations.AlterField(
            model_name='jobscore',
            name='job_type',
            field=models.CharField(choices=[('STUDENT', 'دانشجو'), ('EMPLOYEE', 'کارمند'), ('WORKER', 'کارگر'), ('SALESPERSON', 'فروشنده'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('HARD_JOBS', 'مشاغل سخت'), ('ATHLETE', 'ورزشکار'), ('HOUSEKEEPER', 'خانه دار'), ('MANAGEMENT', 'مدیریت')], default='EMPLOYEE', max_length=14),
        ),
    ]
