# Generated by Django 5.0.4 on 2024-05-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_herb_herb_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('FAST', 'تند'), ('BITTER', 'تلخ'), ('SWEET', 'شیرین'), ('SOUR', 'ترش')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
        migrations.AlterField(
            model_name='seasonalscore',
            name='score',
            field=models.IntegerField(choices=[(2, 'اولویت اول'), (1, 'اولویت دوم'), (-1, 'توصیه نمیشود'), (-2, 'تشدیدکننده ی آلرژی')]),
        ),
    ]
