# Generated by Django 5.0.4 on 2024-05-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_herb_interaction_herb_delete_herbinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(choices=[('SOUR', 'ترش'), ('BITTER', 'تلخ'), ('SWEET', 'شیرین'), ('FAST', 'تند')], default='SWEET', help_text='Select the flavor of the herb.', max_length=10),
        ),
    ]
