# Generated by Django 5.0.4 on 2024-05-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_herb_herb_flavor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agerange',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='agerange',
            name='min_age',
        ),
        migrations.AddField(
            model_name='agerange',
            name='category',
            field=models.CharField(blank=True, choices=[('BABY', 'خردسال'), ('CHILD', 'کودک'), ('TEEN', 'نوجوان'), ('ADULT', 'جوان'), ('MIDDLE_AGED', 'میانسال'), ('ELDER', 'سالمند')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('BITTER', 'تلخ'), ('FAST', 'تند'), ('SOUR', 'ترش'), ('SWEET', 'شیرین')], help_text='Select the flavor of the herb.', max_length=10),
        ),
    ]
