# Generated by Django 5.0.4 on 2024-05-23 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_herb_herb_flavor_alter_seasonalscore_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='unsuitable_jobs',
            field=models.ManyToManyField(blank=True, related_name='unsuitable_herbs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('SOUR', 'ترش'), ('SWEET', 'شیرین'), ('BITTER', 'تلخ'), ('FAST', 'تند')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
    ]
