# Generated by Django 5.0.4 on 2024-05-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_remove_agerange_max_age_remove_agerange_min_age_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgeRange',
            new_name='AgeCategory',
        ),
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('SWEET', 'شیرین'), ('BITTER', 'تلخ'), ('FAST', 'تند'), ('SOUR', 'ترش')], help_text='Select the flavor of the herb.', max_length=10),
        ),
    ]
