# Generated by Django 5.0.4 on 2024-05-23 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_herb_unsuitable_jobs_alter_herb_herb_flavor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herb',
            name='unsuitable_jobs',
        ),
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('BITTER', 'تلخ'), ('SWEET', 'شیرین'), ('SOUR', 'ترش'), ('FAST', 'تند')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
        migrations.CreateModel(
            name='JobScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('WORKER', 'کارگر'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('STUDENT', 'دانشجو'), ('MANAGEMENT', 'مدیریت'), ('SALESPERSON', 'فروشنده'), ('HARD_JOBS', 'مشاغل سخت'), ('EMPLOYEE', 'کارمند'), ('ATHLETE', 'ورزشکار'), ('HOUSEKEEPER', 'خانه دار')], max_length=14)),
                ('score', models.IntegerField(choices=[(2, 'اولویت اول'), (1, 'اولویت دوم'), (-1, 'با احتیاط مصرف کنند'), (-2, 'توصیه نمیشود')], default='2')),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_scores', to='cms.herb')),
            ],
            options={
                'unique_together': {('herb', 'job_type')},
            },
        ),
    ]
