# Generated by Django 5.0.4 on 2024-05-08 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_rename_agerange_agecategory_alter_herb_herb_flavor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agecategory',
            old_name='category',
            new_name='age_category',
        ),
        migrations.RemoveField(
            model_name='herb',
            name='inappropriate_age_ranges',
        ),
        migrations.AddField(
            model_name='agecategory',
            name='herb',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='age_category', to='cms.herb'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('SOUR', 'ترش'), ('SWEET', 'شیرین'), ('BITTER', 'تلخ'), ('FAST', 'تند')], help_text='Select the flavor of the herb.', max_length=10),
        ),
    ]
