# Generated by Django 5.0.4 on 2024-05-23 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_remove_herb_unsuitable_jobs_alter_herb_herb_flavor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('FAST', 'تند'), ('SWEET', 'شیرین'), ('SOUR', 'ترش'), ('BITTER', 'تلخ')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
        migrations.AlterField(
            model_name='jobscore',
            name='job_type',
            field=models.CharField(choices=[('SENSITIVE_JOBS', 'مشاغل حساس'), ('STUDENT', 'دانشجو'), ('WORKER', 'کارگر'), ('ATHLETE', 'ورزشکار'), ('HARD_JOBS', 'مشاغل سخت'), ('HOUSEKEEPER', 'خانه دار'), ('MANAGEMENT', 'مدیریت'), ('SALESPERSON', 'فروشنده'), ('EMPLOYEE', 'کارمند')], max_length=14),
        ),
        migrations.CreateModel(
            name='JobPollutionLevelScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_pollution_level', models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('MUCH', 'زیاد'), ('POLLUTED_JOBS', 'مشاغل آلوده')], default='LOW', max_length=14)),
                ('score', models.IntegerField(choices=[(2, 'اولویت اول'), (1, 'اولویت دوم'), (-1, 'با احتیاط مصرف شود'), (-2, 'توصیه نمیشود')], default='2')),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollution_scores', to='cms.herb')),
            ],
            options={
                'unique_together': {('herb', 'job_pollution_level')},
            },
        ),
    ]
