# Generated by Django 5.0.4 on 2024-05-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_herb_herb_flavor_alter_jobscore_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('SOUR', 'ترش'), ('BITTER', 'تلخ'), ('FAST', 'تند'), ('SWEET', 'شیرین')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
        migrations.AlterField(
            model_name='jobpollutionlevelscore',
            name='job_pollution_level',
            field=models.CharField(blank=True, choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('MUCH', 'زیاد'), ('POLLUTED_JOBS', 'مشاغل آلوده')], max_length=14),
        ),
        migrations.AlterField(
            model_name='jobscore',
            name='job_type',
            field=models.CharField(choices=[('HARD_JOBS', 'مشاغل سخت'), ('HOUSEKEEPER', 'خانه دار'), ('WORKER', 'کارگر'), ('SALESPERSON', 'فروشنده'), ('MANAGEMENT', 'مدیریت'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('ATHLETE', 'ورزشکار'), ('STUDENT', 'دانشجو'), ('EMPLOYEE', 'کارمند')], max_length=14),
        ),
    ]
