# Generated by Django 5.0.4 on 2024-05-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_rename_category_agecategory_age_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgeCategory',
            new_name='AgeCategoryForbiddenHerb',
        ),
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('BITTER', 'تلخ'), ('SWEET', 'شیرین'), ('FAST', 'تند'), ('SOUR', 'ترش')], help_text='Select the flavor of the herb.', max_length=10),
        ),
    ]
