# Generated by Django 5.0.4 on 2024-05-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_herb_herb_flavor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpollutionlevelscore',
            old_name='job_pollution_level',
            new_name='job_pollution',
        ),
        migrations.AlterUniqueTogether(
            name='jobpollutionlevelscore',
            unique_together={('herb', 'job_pollution')},
        ),
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('SWEET', 'شیرین'), ('FAST', 'تند'), ('BITTER', 'تلخ'), ('SOUR', 'ترش')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
        migrations.AlterField(
            model_name='jobpollutionlevelscore',
            name='score',
            field=models.IntegerField(choices=[(2, 'عالی'), (1, 'خوب'), (0, 'خنثی'), (-1, 'با احتیاط مصرف شود'), (-2, 'توصیه نمیشود')], default='0'),
        ),
        migrations.AlterField(
            model_name='jobscore',
            name='job_type',
            field=models.CharField(choices=[('STUDENT', 'دانشجو'), ('EMPLOYEE', 'کارمند'), ('WORKER', 'کارگر'), ('SALESPERSON', 'فروشنده'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('HARD_JOBS', 'مشاغل سخت'), ('ATHLETE', 'ورزشکار'), ('HOUSEKEEPER', 'خانه دار'), ('MANAGEMENT', 'مدیریت')], max_length=14),
        ),
        migrations.AlterField(
            model_name='jobscore',
            name='score',
            field=models.IntegerField(choices=[(2, 'عالی'), (1, 'خوب'), (0, 'خنثی'), (-1, 'با احتیاط مصرف کنند'), (-2, 'توصیه نمیشود')], default='0'),
        ),
    ]
