# Generated by Django 5.0.4 on 2024-05-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_rename_agecategory_agecategoryforbiddenherb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('BABY', 'خردسال'), ('CHILD', 'کودک'), ('TEEN', 'نوجوان'), ('ADULT', 'جوان'), ('MIDDLE_AGED', 'میانسال'), ('ELDER', 'سالمند')], max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('FAST', 'تند'), ('SWEET', 'شیرین'), ('BITTER', 'تلخ'), ('SOUR', 'ترش')], help_text='Select the flavor of the herb.', max_length=10),
        ),
        migrations.AddField(
            model_name='herb',
            name='inappropriate_age_ranges',
            field=models.ManyToManyField(blank=True, to='cms.agecategory', verbose_name='بازه\u200cهای سنی نامناسب'),
        ),
        migrations.DeleteModel(
            name='AgeCategoryForbiddenHerb',
        ),
    ]
