# Generated by Django 5.0.4 on 2024-05-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_agecategory_alter_herb_herb_flavor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agecategory',
            name='category',
        ),
        migrations.AddField(
            model_name='agecategory',
            name='max_age',
            field=models.IntegerField(default=35, verbose_name='حداکثر سن'),
        ),
        migrations.AddField(
            model_name='agecategory',
            name='min_age',
            field=models.IntegerField(default=18, verbose_name='حداقل سن'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('FAST', 'تند'), ('BITTER', 'تلخ'), ('SWEET', 'شیرین'), ('SOUR', 'ترش')], help_text='Select the flavor of the herb.', max_length=10),
        ),
    ]
