# Generated by Django 5.0.4 on 2024-05-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_rename_job_pollution_level_jobpollutionlevelscore_job_pollution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('SWEET', 'شیرین'), ('BITTER', 'تلخ'), ('FAST', 'تند'), ('SOUR', 'ترش')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
    ]
