# Generated by Django 5.0.4 on 2024-05-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_remove_agecategory_category_agecategory_max_age_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgeCategory',
            new_name='AgeRange',
        ),
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('BITTER', 'تلخ'), ('SOUR', 'ترش'), ('FAST', 'تند'), ('SWEET', 'شیرین')], help_text='Select the flavor of the herb.', max_length=10),
        ),
    ]
