# Generated by Django 5.0.4 on 2024-05-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_rename_agecategory_agerange_alter_herb_herb_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agerange',
            name='max_age',
            field=models.IntegerField(verbose_name='حداکثر سن'),
        ),
        migrations.AlterField(
            model_name='agerange',
            name='min_age',
            field=models.IntegerField(verbose_name='حداقل سن'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('SWEET', 'شیرین'), ('SOUR', 'ترش'), ('FAST', 'تند'), ('BITTER', 'تلخ')], help_text='Select the flavor of the herb.', max_length=10),
        ),
    ]
