# Generated by Django 5.0.4 on 2024-05-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_alter_agerange_max_age_alter_agerange_min_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('SWEET', 'شیرین'), ('FAST', 'تند'), ('BITTER', 'تلخ'), ('SOUR', 'ترش')], help_text='Select the flavor of the herb.', max_length=10),
        ),
        migrations.AlterField(
            model_name='suitability',
            name='score',
            field=models.IntegerField(choices=[('3', 'درمان اول'), ('2', 'درمان دوم'), ('1', 'درمان سوم'), ('-100', 'غدقن')]),
        ),
    ]
