# Generated by Django 5.0.4 on 2024-05-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_alter_herb_herb_flavor_alter_suitability_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('FAST', 'تند'), ('SOUR', 'ترش'), ('BITTER', 'تلخ'), ('SWEET', 'شیرین')], help_text='Select the flavor of the herb.', max_length=10),
        ),
        migrations.AlterField(
            model_name='suitability',
            name='negative_effects',
            field=models.CharField(blank=True, choices=[('consultation_needed', 'نیاز به مشورت به پزشک دارد'), ('contradiction', 'تعارض دارد')], max_length=100, null=True, verbose_name='حالت منفی'),
        ),
        migrations.AlterField(
            model_name='suitability',
            name='score',
            field=models.IntegerField(choices=[('3', 'درمان اول'), ('2', 'درمان دوم'), ('1', 'درمان سوم'), ('-100', 'قدغن است')], verbose_name='اولویت درمان'),
        ),
    ]
