# Generated by Django 5.0.4 on 2024-05-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_alter_herb_herb_flavor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('BITTER', 'تلخ'), ('SWEET', 'شیرین'), ('FAST', 'تند'), ('SOUR', 'ترش')], help_text='Select the flavor of the herb.', max_length=10),
        ),
        migrations.AlterField(
            model_name='suitability',
            name='negative_effects',
            field=models.CharField(blank=True, choices=[('consultation_needed', 'نیاز به مشورت به پزشک دارد'), ('contradiction', 'تعارض دارد')], max_length=100, null=True, verbose_name='حالات هشدار'),
        ),
    ]
