# Generated by Django 5.0.4 on 2024-05-14 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_alter_herb_herb_flavor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام بیماری'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('SOUR', 'ترش'), ('FAST', 'تند'), ('BITTER', 'تلخ'), ('SWEET', 'شیرین')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام گیاه'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='temperament',
            field=models.CharField(choices=[('COLD', 'سرد'), ('HOT', 'گرم'), ('BOTH', 'هردو')], default='COLD', help_text='Select the temperament category of the herb.', max_length=10, verbose_name='طبع گیاه'),
        ),
        migrations.AlterField(
            model_name='seasonalscore',
            name='herb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_scores', to='cms.herb', verbose_name='گیاه'),
        ),
        migrations.AlterField(
            model_name='seasonalscore',
            name='season',
            field=models.CharField(choices=[('SPRING', 'بهار'), ('SUMMER', 'تابستان'), ('AUTUMN', 'پاییز'), ('WINTER', 'زمستان')], max_length=10, verbose_name='فصل'),
        ),
        migrations.AlterField(
            model_name='suitability',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suitability_disease', to='cms.disease', verbose_name='بیماری'),
        ),
        migrations.AlterField(
            model_name='suitability',
            name='herb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suitability_herb', to='cms.herb', verbose_name='گیاه'),
        ),
    ]
