# Generated by Django 5.0.4 on 2024-05-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_alter_disease_name_alter_herb_herb_flavor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('SOUR', 'ترش'), ('FAST', 'تند'), ('SWEET', 'شیرین'), ('BITTER', 'تلخ')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
        migrations.AlterField(
            model_name='suitability',
            name='score',
            field=models.IntegerField(choices=[(3, 'درمان اول'), (2, 'درمان دوم'), (1, 'درمان سوم'), (-100, 'قدغن است')], verbose_name='اولویت درمان'),
        ),
    ]
