# Generated by Django 5.0.4 on 2024-05-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_disease_similar_names_alter_herb_herb_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, default='Description', null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('FAST', 'تند'), ('SWEET', 'شیرین'), ('SOUR', 'ترش'), ('BITTER', 'تلخ')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
    ]
