# Generated by Django 5.0.4 on 2024-05-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_alter_disease_description_alter_herb_herb_flavor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='description',
        ),
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('BITTER', 'تلخ'), ('FAST', 'تند'), ('SOUR', 'ترش'), ('SWEET', 'شیرین')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
    ]
