# Generated by Django 5.0.4 on 2024-05-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_remove_disease_description_alter_herb_herb_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('FAST', 'تند'), ('BITTER', 'تلخ'), ('SOUR', 'ترش'), ('SWEET', 'شیرین')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
        migrations.AlterField(
            model_name='suitability',
            name='score',
            field=models.IntegerField(choices=[(3, 'درمان اول'), (2, 'درمان دوم'), (1, 'درمان سوم'), (-1, 'توصیه نمیشود'), (-100, 'قدغن است')], verbose_name='اولویت درمان'),
        ),
    ]
