# Generated by Django 5.0.4 on 2024-05-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_alter_herb_herb_flavor_alter_suitability_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suitability',
            old_name='negative_effects',
            new_name='alert_states',
        ),
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('SOUR', 'ترش'), ('SWEET', 'شیرین'), ('FAST', 'تند'), ('BITTER', 'تلخ')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
    ]
