# Generated by Django 5.0.4 on 2024-05-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_rename_negative_effects_suitability_alert_states_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='herb_flavor',
            field=models.CharField(blank=True, choices=[('SWEET', 'شیرین'), ('BITTER', 'تلخ'), ('SOUR', 'ترش'), ('FAST', 'تند')], help_text='Select the flavor of the herb.', max_length=10, verbose_name='مزه گیاه'),
        ),
    ]
