# Generated by Django 5.0.1 on 2024-02-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_comment_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Comment text'),
        ),
    ]
