# Generated by Django 5.0.1 on 2024-02-03 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_discount_title_alter_comment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounts',
            new_name='discount',
        ),
    ]
