# Generated by Django 5.0.2 on 2024-02-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_main_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='Tracking Code'),
        ),
    ]
