# Generated by Django 5.0.4 on 2024-04-25 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('temperature', models.CharField(choices=[('COLD', 'Cold'), ('HOT', 'Hot')], default='COLD', help_text='Select the temperature category of the herb.', max_length=10)),
                ('suitable_season', models.CharField(choices=[('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('AUTUMN', 'Autumn'), ('WINTER', 'Winter')], default='SPRING', help_text='Select the suitable season for the herb.', max_length=10)),
                ('age_group', models.CharField(choices=[('INFANT', 'Infant'), ('CHILD', 'Child'), ('TEEN', 'Teen'), ('ADULT', 'Adult'), ('MIDDLE_AGED', 'Middle Aged'), ('SENIOR', 'Senior')], default='ADULT', help_text='Select the suitable age group for the herb.', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NeutralPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Suitability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.disease')),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.herb')),
            ],
        ),
    ]
