# Generated by Django 5.0.4 on 2024-04-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herb',
            name='temperature',
        ),
        migrations.AddField(
            model_name='herb',
            name='temperament',
            field=models.CharField(choices=[('COLD', 'Cold'), ('HOT', 'Hot')], default='COLD', help_text='Select the temperament category of the herb.', max_length=10),
        ),
    ]
