# Generated by Django 5.0.4 on 2024-05-23 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_herb_herb_flavor_alter_seasonalscore_score_and_more'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='type',
            field=models.CharField(choices=[('دمنوش', 'دمنوش'), ('بسته', 'بسته'), ('فله', 'فله')], default='دمنوش', max_length=6),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('دمنوش', 'دمنوش'), ('بسته', 'بسته'), ('فله', 'فله')], default='دمنوش', max_length=6),
        ),
        migrations.RemoveField(
            model_name='product',
            name='herb',
        ),
        migrations.AddField(
            model_name='product',
            name='herb',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cms.herb'),
        ),
    ]
