# Generated by Django 5.0.4 on 2024-06-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_seasonalscore_allergy_aggravator_alter_comment_post_and_more'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='herb',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='type',
            field=models.CharField(choices=[('دمنوش', 'دمنوش'), ('بسته', 'بسته'), ('فله', 'فله')], default='دمنوش', max_length=6),
        ),
        migrations.AddField(
            model_name='product',
            name='herbs',
            field=models.ManyToManyField(related_name='products', to='cms.herb'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('دمنوش', 'دمنوش'), ('بسته', 'بسته'), ('فله', 'فله')], default='دمنوش', max_length=6),
        ),
    ]
