# Generated by Django 5.0.4 on 2024-05-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='type',
            field=models.CharField(choices=[('دمنوش', 'دمنوش'), ('بسته', 'بسته'), ('فله', 'فله')], default='دمنوش', max_length=6),
        ),
    ]
