# Generated by Django 5.0.4 on 2024-05-23 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_herb_herb_flavor'),
        ('shop', '0002_orderitems_type_product_type_remove_product_herb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='herb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cms.herb'),
        ),
    ]
