# Generated by Django 5.0.4 on 2024-04-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_herb_temperature_herb_temperament'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='negative_states',
            field=models.CharField(choices=[('CONSULT', 'نیاز به مشورت به پزشک دارد'), ('CONFLICT', 'تعارض دارد'), ('FORBIDDEN', 'قدغن است')], default='CONSULT', help_text='Select the negative state of the herb if applicable.', max_length=10),
        ),
        migrations.AddField(
            model_name='herb',
            name='primary_functions',
            field=models.ManyToManyField(blank=True, help_text='Select up to three primary functions of the herb for diseases.', related_name='herbs_with_primary_function', to='shop.disease'),
        ),
    ]
