# Generated by Django 5.0.4 on 2024-05-22 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_herb_herb_flavor'),
        ('shop', '0003_orderitems_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='herb',
        ),
        migrations.AddField(
            model_name='product',
            name='herb',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cms.herb'),
        ),
    ]
