# Generated by Django 5.0.4 on 2024-04-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_herb_negative_states_herb_primary_functions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herb',
            name='negative_states',
        ),
        migrations.RemoveField(
            model_name='herb',
            name='primary_functions',
        ),
        migrations.AddField(
            model_name='suitability',
            name='negative_states',
            field=models.CharField(choices=[('CONSULT', 'نیاز به مشورت به پزشک دارد'), ('CONFLICT', 'تعارض دارد'), ('FORBIDDEN', 'قدغن است')], default='CONSULT', help_text='Select the negative state of the herb if applicable.', max_length=10),
        ),
    ]
