# Generated by Django 5.0.4 on 2024-05-22 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_herb_herb_flavor'),
        ('shop', '0004_remove_product_herb_product_herb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='herb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cms.herb'),
        ),
    ]
