# Generated by Django 5.0.4 on 2024-04-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_herb_negative_states_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herb',
            name='age_group',
        ),
        migrations.AddField(
            model_name='suitability',
            name='herb_properties',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='suitability',
            name='negative_states',
            field=models.CharField(choices=[('ALLOWED', 'مجاز است'), ('CONSULT', 'نیاز به مشورت به پزشک دارد'), ('CONFLICT', 'تعارض دارد'), ('FORBIDDEN', 'قدغن است')], default='CONSULT', help_text='Select the negative state of the herb if applicable.', max_length=10),
        ),
    ]
