# Generated by Django 5.0.4 on 2024-05-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_alter_herb_herb_flavor'),
        ('shop', '0005_alter_product_herb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='herb',
        ),
        migrations.AddField(
            model_name='product',
            name='herb',
            field=models.ManyToManyField(related_name='products', to='cms.herb'),
        ),
    ]
