# Generated by Django 5.0.4 on 2024-04-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_herb_age_group_suitability_herb_properties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='suitable_season',
            field=models.CharField(choices=[('SPRING', 'بهار'), ('SUMMER', 'تابستان'), ('AUTUMN', 'پاییز'), ('WINTER', 'زمستان')], default='SPRING', help_text='Select the suitable season for the herb.', max_length=10),
        ),
    ]
