# Generated by Django 5.0.4 on 2024-05-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_herb_product_herb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='herb',
            new_name='herbs',
        ),
    ]
