# Generated by Django 5.0.4 on 2024-04-28 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_herb_suitable_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitability',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suitability_disease', to='shop.disease'),
        ),
        migrations.AlterField(
            model_name='suitability',
            name='herb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suitability_herb', to='shop.herb'),
        ),
    ]
