# Generated by Django 5.0.4 on 2024-04-30 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_suitability_disease_alter_suitability_herb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='suitability',
            unique_together={('herb', 'disease')},
        ),
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(default='Description', verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='herb',
            name='negative_effects',
            field=models.CharField(choices=[('consultation_needed', 'نیاز به مشورت به پزشک دارد'), ('contradiction', 'تعارض دارد'), ('prohibited', 'قدغن است')], default='consultation_needed', max_length=100, verbose_name='حالت منفی'),
        ),
        migrations.AddField(
            model_name='herb',
            name='primary_use',
            field=models.TextField(default='1', verbose_name='کاربرد اصلی'),
        ),
        migrations.RemoveField(
            model_name='suitability',
            name='herb_properties',
        ),
        migrations.RemoveField(
            model_name='suitability',
            name='negative_states',
        ),
        migrations.CreateModel(
            name='UserDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.disease', verbose_name='بیماری')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'unique_together': {('user', 'disease')},
            },
        ),
    ]
