# Generated by Django 5.0.4 on 2024-04-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_herb_negative_effects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='negative_effects',
            field=models.CharField(blank=True, choices=[('consultation_needed', 'نیاز به مشورت به پزشک دارد'), ('contradiction', 'تعارض دارد'), ('prohibited', 'قدغن است')], max_length=100, null=True, verbose_name='حالت منفی'),
        ),
    ]
