# Generated by Django 5.0.4 on 2024-04-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_herb_negative_effects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='temperament',
            field=models.CharField(choices=[('COLD', 'سرد'), ('HOT', 'گرم')], default='COLD', help_text='Select the temperament category of the herb.', max_length=10),
        ),
    ]
