# Generated by Django 5.0.4 on 2024-04-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_herb_temperament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='primary_use',
            field=models.TextField(verbose_name='کاربرد اصلی'),
        ),
    ]
