# Generated by Django 5.0.1 on 2024-02-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='stars',
            field=models.CharField(choices=[('1', 'Very Bad'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Good'), ('5', 'Perfect')], default='3', max_length=10, verbose_name='Your score?'),
        ),
    ]
