# Generated by Django 5.0.1 on 2024-02-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_image_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_stars',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
