# Generated by Django 5.0.1 on 2024-02-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_average_stars_product_sales_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_stars',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_count',
        ),
    ]
