# Generated by Django 5.0.2 on 2024-02-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_order_status_order_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phon_number',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='-', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='-', max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='-', max_length=20, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(default='-', max_length=100, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=700, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
    ]
