# Generated by Django 5.0.4 on 2024-05-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('fullname', models.CharField(max_length=100)),
                ('job_pollution_level', models.CharField(blank=True, choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('MUCH', 'زیاد'), ('POLLUTED_JOBS', 'مشاغل آلوده')], max_length=14, null=True, verbose_name='سطج آلودگی شغل')),
                ('job_category', models.CharField(blank=True, choices=[('ATHLETE', 'ورزشکار'), ('HARD_JOBS', 'مشاغل سخت'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('SALESPERSON', 'فروشنده'), ('MANAGEMENT', 'مدیریت'), ('STUDENT', 'دانشجو'), ('WORKER', 'کارگر'), ('HOUSEKEEPER', 'خانه دار'), ('EMPLOYEE', 'کارمند')], max_length=15, null=True)),
                ('seasonal_allergy', models.CharField(blank=True, choices=[('SPRING', 'بهار'), ('SUMMER', 'تابستان'), ('FALL', 'پاییز'), ('WINTER', 'زمستان')], max_length=10, null=True, verbose_name='آلرژی فصلی ')),
                ('taste_sensitivity', models.CharField(blank=True, choices=[('SOUR', 'ترش'), ('SWEET', 'شیرین'), ('FAST', 'تند'), ('BITTER', 'تلخ')], max_length=10, null=True, verbose_name='حساسیت به طعم')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('Male', 'مرد'), ('Female', 'زن')], max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
