# Generated by Django 5.0.4 on 2024-06-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cms', '0002_seasonalscore_allergy_aggravator_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disease',
            field=models.ManyToManyField(blank=True, to='cms.disease'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, choices=[('SENSITIVE_JOBS', 'مشاغل حساس'), ('STUDENT', 'دانشجو'), ('SALESPERSON', 'فروشنده'), ('MANAGEMENT', 'مدیریت'), ('EMPLOYEE', 'کارمند'), ('ATHLETE', 'ورزشکار'), ('HOUSEKEEPER', 'خانه دار'), ('HARD_JOBS', 'مشاغل سخت'), ('WORKER', 'کارگر')], max_length=15, null=True),
        ),
    ]
