# Generated by Django 5.0.4 on 2024-05-04 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('code', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='09151234567', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_pollution_level', models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('MUCH', 'زیاد'), ('POLLUTED_JOBS', 'مشاغل آلوده')], max_length=13, verbose_name='سطج آلودگی شغل')),
                ('job_category', models.CharField(choices=[('STUDENT', 'دانشجو'), ('CLERK', 'کارمند'), ('WORKER', 'کارگر'), ('SALESPERSON', 'فروشنده'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('HARD_JOBS', 'مشاغل سخت'), ('ATHLETE', 'ورزشکار'), ('HOMEMAKER', 'خانه دار'), ('MANAGEMENT', 'مدیریت')], max_length=55, verbose_name='شغل کاربر')),
                ('seasonal_allergy', models.CharField(blank=True, choices=[('SPRING', 'بهار'), ('SUMMER', 'تابستان'), ('FALL', 'پاییز'), ('WINTER', 'زمستان')], max_length=10, null=True, verbose_name='آلرژی فصلی ')),
                ('taste_sensitivity', models.CharField(blank=True, choices=[('SOUR', 'ترش'), ('SWEET', 'شیرین'), ('FAST', 'تند'), ('BITTER', 'تلخ')], max_length=10, null=True, verbose_name='حساسیت به طعم')),
                ('age_category', models.CharField(choices=[('BABY', 'خردسال'), ('CHILD', 'کودک'), ('TEEN', 'نوجوان'), ('ADULT', 'جوان'), ('MIDDLE_AGED', 'میانسال'), ('ELDER', 'سالمند')], max_length=11, verbose_name='رده سنی ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
