# Generated by Django 5.0.4 on 2024-05-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disease',
            field=models.ManyToManyField(blank=True, to='cms.disease'),
        ),
    ]
