# Generated by Django 5.0.4 on 2024-04-27 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('shop', '0005_remove_herb_age_group_suitability_herb_properties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('INFANT', 'خردسال'), ('CHILD', 'کودک'), ('TEEN', 'نوجوان'), ('YOUNG_ADULT', 'جوان'), ('MIDDLE_AGED', 'میانسال'), ('SENIOR', 'سالمند')], default='YOUNG_ADULT', help_text='رده سنی کاربر را انتخاب کنید.', max_length=15)),
                ('occupation', models.CharField(choices=[('STUDENT', 'دانشجو'), ('EMPLOYEE', 'کارمند'), ('WORKER', 'کارگر'), ('SALESPERSON', 'فروشنده'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('HARD_JOBS', 'مشاغل سخت'), ('ATHLETE', 'ورزشکار'), ('HOUSEKEEPER', 'خانه دار'), ('MANAGEMENT', 'مدیریت')], default='EMPLOYEE', help_text='نوع شغل کاربر را انتخاب کنید.', max_length=20)),
                ('pollution_level', models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('HIGH', 'زیاد'), ('POLLUTED_JOBS', 'مشاغل آلوده')], default='LOW', help_text='سطح آلودگی محیط کاری کاربر را انتخاب کنید.', max_length=15)),
                ('taste_restrictions', models.CharField(choices=[('SOUR', 'ترش'), ('SWEET', 'شیرین'), ('SPICY', 'تند'), ('BITTER', 'تلخ')], default='SOUR', help_text='حساسیت یا ممنوعیت به طعم\u200cها را انتخاب کنید.', max_length=10)),
                ('seasonal_allergies', models.ManyToManyField(blank=True, help_text='آلرژی های فصلی کاربر را انتخاب کنید.', related_name='users_with_seasonal_allergies', to='shop.disease')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
