# Generated by Django 5.0.4 on 2024-05-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cms', '0002_alter_herb_herb_flavor_alter_seasonalscore_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disease',
            field=models.ManyToManyField(blank=True, to='cms.disease'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, choices=[('SENSITIVE_JOBS', 'مشاغل حساس'), ('EMPLOYEE', 'کارمند'), ('ATHLETE', 'ورزشکار'), ('HARD_JOBS', 'مشاغل سخت'), ('SALESPERSON', 'فروشنده'), ('HOUSEKEEPER', 'خانه دار'), ('MANAGEMENT', 'مدیریت'), ('WORKER', 'کارگر'), ('STUDENT', 'دانشجو')], max_length=15, null=True),
        ),
    ]
