# Generated by Django 5.0.4 on 2024-04-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='seasonal_allergies',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seasonal_allergies',
            field=models.CharField(choices=[('SPRING', 'بهار'), ('SUMMER', 'تابستان'), ('AUTUMN', 'پاییز'), ('WINTER', 'زمستان')], default='SPRING', help_text='آلرژی های فصلی کاربر را انتخاب کنید.', max_length=10),
        ),
    ]
