# Generated by Django 5.0.4 on 2024-05-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, choices=[('WORKER', 'کارگر'), ('MANAGEMENT', 'مدیریت'), ('HOUSEKEEPER', 'خانه دار'), ('SALESPERSON', 'فروشنده'), ('STUDENT', 'دانشجو'), ('ATHLETE', 'ورزشکار'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('EMPLOYEE', 'کارمند'), ('HARD_JOBS', 'مشاغل سخت')], max_length=15, null=True),
        ),
    ]
