# Generated by Django 5.0.4 on 2024-06-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_disease_alter_user_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, choices=[('STUDENT', 'دانشجو'), ('MANAGEMENT', 'مدیریت'), ('WORKER', 'کارگر'), ('EMPLOYEE', 'کارمند'), ('ATHLETE', 'ورزشکار'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('HARD_JOBS', 'مشاغل سخت'), ('HOUSEKEEPER', 'خانه دار'), ('SALESPERSON', 'فروشنده')], max_length=15, null=True),
        ),
    ]
