# Generated by Django 5.0.4 on 2024-05-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_disease_alter_user_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, choices=[('HARD_JOBS', 'مشاغل سخت'), ('SALESPERSON', 'فروشنده'), ('STUDENT', 'دانشجو'), ('HOUSEKEEPER', 'خانه دار'), ('ATHLETE', 'ورزشکار'), ('EMPLOYEE', 'کارمند'), ('MANAGEMENT', 'مدیریت'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('WORKER', 'کارگر')], max_length=15, null=True),
        ),
    ]
