# Generated by Django 5.0.4 on 2024-06-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, choices=[('SENSITIVE_JOBS', 'مشاغل حساس'), ('HOUSEKEEPER', 'خانه دار'), ('WORKER', 'کارگر'), ('STUDENT', 'دانشجو'), ('EMPLOYEE', 'کارمند'), ('HARD_JOBS', 'مشاغل سخت'), ('SALESPERSON', 'فروشنده'), ('MANAGEMENT', 'مدیریت'), ('ATHLETE', 'ورزشکار')], max_length=15, null=True),
        ),
    ]
