# Generated by Django 5.0.4 on 2024-06-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, choices=[('MANAGEMENT', 'مدیریت'), ('SALESPERSON', 'فروشنده'), ('ATHLETE', 'ورزشکار'), ('WORKER', 'کارگر'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('EMPLOYEE', 'کارمند'), ('HOUSEKEEPER', 'خانه دار'), ('STUDENT', 'دانشجو'), ('HARD_JOBS', 'مشاغل سخت')], max_length=15, null=True),
        ),
    ]
