# Generated by Django 5.0.4 on 2024-05-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, choices=[('ATHLETE', 'ورزشکار'), ('STUDENT', 'دانشجو'), ('SALESPERSON', 'فروشنده'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('HOUSEKEEPER', 'خانه دار'), ('MANAGEMENT', 'مدیریت'), ('WORKER', 'کارگر'), ('HARD_JOBS', 'مشاغل سخت'), ('EMPLOYEE', 'کارمند')], max_length=15, null=True),
        ),
    ]
