# Generated by Django 5.0.4 on 2024-06-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, choices=[('SALESPERSON', 'فروشنده'), ('STUDENT', 'دانشجو'), ('HARD_JOBS', 'مشاغل سخت'), ('MANAGEMENT', 'مدیریت'), ('HOUSEKEEPER', 'خانه دار'), ('ATHLETE', 'ورزشکار'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('EMPLOYEE', 'کارمند'), ('WORKER', 'کارگر')], max_length=15, null=True),
        ),
    ]
