# Generated by Django 5.0.4 on 2024-06-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, choices=[('HOUSEKEEPER', 'خانه دار'), ('SALESPERSON', 'فروشنده'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('MANAGEMENT', 'مدیریت'), ('HARD_JOBS', 'مشاغل سخت'), ('EMPLOYEE', 'کارمند'), ('ATHLETE', 'ورزشکار'), ('WORKER', 'کارگر'), ('STUDENT', 'دانشجو')], max_length=15, null=True),
        ),
    ]
