# Generated by Django 5.0.4 on 2024-04-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otpcode_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activity',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_category',
            field=models.CharField(choices=[('BABY', 'خردسال'), ('CHILD', 'کودک'), ('TEEN', 'نوجوان'), ('ADULT', 'جوان'), ('MIDDLE_AGED', 'میانسال'), ('ELDER', 'سالمند')], default='ADULT', max_length=11, verbose_name='رده سنی '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_category',
            field=models.CharField(choices=[('STUDENT', 'دانشجو'), ('CLERK', 'کارمند'), ('WORKER', 'کارگر'), ('SALESPERSON', 'فروشنده'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('HARD_JOBS', 'مشاغل سخت'), ('ATHLETE', 'ورزشکار'), ('HOMEMAKER', 'خانه دار'), ('MANAGEMENT', 'مدیریت')], default='CLERK', max_length=55, verbose_name='شغل کاربر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_pollution_level',
            field=models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('MUCH', 'زیاد'), ('POLLUTED_JOBS', 'مشاغل آلوده')], default='MEDIUM', max_length=13, verbose_name='سطج آلودگی شغل'),
        ),
    ]
