# Generated by Django 5.0.4 on 2024-05-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, choices=[('WORKER', 'کارگر'), ('ATHLETE', 'ورزشکار'), ('STUDENT', 'دانشجو'), ('EMPLOYEE', 'کارمند'), ('MANAGEMENT', 'مدیریت'), ('HOUSEKEEPER', 'خانه دار'), ('SALESPERSON', 'فروشنده'), ('HARD_JOBS', 'مشاغل سخت'), ('SENSITIVE_JOBS', 'مشاغل حساس')], max_length=15, null=True),
        ),
    ]
