# Generated by Django 5.0.4 on 2024-05-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, choices=[('MANAGEMENT', 'مدیریت'), ('HOUSEKEEPER', 'خانه دار'), ('EMPLOYEE', 'کارمند'), ('ATHLETE', 'ورزشکار'), ('HARD_JOBS', 'مشاغل سخت'), ('SALESPERSON', 'فروشنده'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('STUDENT', 'دانشجو'), ('WORKER', 'کارگر')], max_length=15, null=True),
        ),
    ]
