# Generated by Django 5.0.4 on 2024-04-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_pollution_level',
            field=models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('MUCH', 'زیاد'), ('POLLUTED_JOBS', 'مشاغل آلوده')], max_length=13, verbose_name='سطج آلودگی شغل'),
        ),
    ]
