# Generated by Django 5.0.4 on 2024-04-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_job_pollution_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_category',
            field=models.CharField(choices=[('BABY', 'خردسال'), ('CHILD', 'کودک'), ('TEEN', 'نوجوان'), ('ADULT', 'جوان'), ('MIDDLE_AGED', 'میانسال'), ('ELDER', 'سالمند')], max_length=11, verbose_name='رده سنی '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_category',
            field=models.CharField(choices=[('STUDENT', 'دانشجو'), ('CLERK', 'کارمند'), ('WORKER', 'کارگر'), ('SALESPERSON', 'فروشنده'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('HARD_JOBS', 'مشاغل سخت'), ('ATHLETE', 'ورزشکار'), ('HOMEMAKER', 'خانه دار'), ('MANAGEMENT', 'مدیریت')], max_length=55, verbose_name='شغل کاربر'),
        ),
    ]
