# Generated by Django 5.0.4 on 2024-05-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, choices=[('WORKER', 'کارگر'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('STUDENT', 'دانشجو'), ('MANAGEMENT', 'مدیریت'), ('SALESPERSON', 'فروشنده'), ('HARD_JOBS', 'مشاغل سخت'), ('EMPLOYEE', 'کارمند'), ('ATHLETE', 'ورزشکار'), ('HOUSEKEEPER', 'خانه دار')], max_length=15, null=True),
        ),
    ]
