# Generated by Django 5.0.4 on 2024-05-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, choices=[('SENSITIVE_JOBS', 'مشاغل حساس'), ('ATHLETE', 'ورزشکار'), ('WORKER', 'کارگر'), ('STUDENT', 'دانشجو'), ('HOUSEKEEPER', 'خانه دار'), ('HARD_JOBS', 'مشاغل سخت'), ('MANAGEMENT', 'مدیریت'), ('SALESPERSON', 'فروشنده'), ('EMPLOYEE', 'کارمند')], max_length=15, null=True),
        ),
    ]
