# Generated by Django 5.0.4 on 2024-05-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, choices=[('HARD_JOBS', 'مشاغل سخت'), ('MANAGEMENT', 'مدیریت'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('WORKER', 'کارگر'), ('SALESPERSON', 'فروشنده'), ('ATHLETE', 'ورزشکار'), ('HOUSEKEEPER', 'خانه دار'), ('STUDENT', 'دانشجو'), ('EMPLOYEE', 'کارمند')], max_length=15, null=True),
        ),
    ]
