# Generated by Django 5.0.4 on 2024-05-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, choices=[('SALESPERSON', 'فروشنده'), ('STUDENT', 'دانشجو'), ('EMPLOYEE', 'کارمند'), ('ATHLETE', 'ورزشکار'), ('MANAGEMENT', 'مدیریت'), ('SENSITIVE_JOBS', 'مشاغل حساس'), ('HARD_JOBS', 'مشاغل سخت'), ('WORKER', 'کارگر'), ('HOUSEKEEPER', 'خانه دار')], max_length=15, null=True),
        ),
    ]
