# Generated by Django 5.0.4 on 2024-05-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, choices=[('HARD_JOBS', 'مشاغل سخت'), ('STUDENT', 'دانشجو'), ('ATHLETE', 'ورزشکار'), ('SALESPERSON', 'فروشنده'), ('MANAGEMENT', 'مدیریت'), ('HOUSEKEEPER', 'خانه دار'), ('WORKER', 'کارگر'), ('EMPLOYEE', 'کارمند'), ('SENSITIVE_JOBS', 'مشاغل حساس')], max_length=15, null=True),
        ),
    ]
